version = 1

test_patterns = ["**/?(*.)+(spec|test).(ts|tsx)"]

exclude_patterns = ["src/polyfills/**/*"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]
  plugins = ["react"]
  style_guide = "airbnb"
  dialect = "typescript"
